type: task
name: train-cvgl

# GPU configuration - defaults to 1, but can be set in run configs
gpu: 1

# Resource requirements
resources:
  memory: 32GB
  disk: 100GB

# Python version
python: "3.11"

# Environment variables
env:
  - WANDB_PROJECT=taco
  - PYTHONUNBUFFERED=1

# Setup commands - install dependencies
setup:
  - pip install -e .
  - pip install lightning wandb opencv-python albumentations timm tqdm

# Training command - use variables from run configuration
commands:
  - >
    python examples/train_cvgl.py
    --batch-size ${BATCH_SIZE:-8}
    --embedding-dim ${EMBEDDING_DIM:-512}
    --learning-rate ${LEARNING_RATE:-0.0001}
    --loss-type ${LOSS_TYPE:-ntxent}
    --scheduler-type ${SCHEDULER_TYPE:-cosine}
    --max-epochs ${MAX_EPOCHS:-40}
    --model-name ${MODEL_NAME:-convnext}
    --experiment-name ${EXPERIMENT_NAME:-default}
    --output-dir ${OUTPUT_DIR:-output}
    --devices ${DEVICES:-auto}
    --strategy ${STRATEGY:-auto}
    ${AUTO_BATCH_SIZE:+--auto-batch-size}

# Optional: Ports to expose
ports:
  - 6006  # TensorBoard (if you decide to use it)
